sudo: required

services:
  - docker

language: java

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  # so no port battle between travis and docker
  - sudo service postgresql stop

script:
  - .scripts/run_backend_tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then .scripts/tag_release.sh; fi
